table retail_sales_dataset
	lineageTag: 4ef21742-8408-4b14-a633-8615865d551e

	column 'Transaction ID'
		dataType: int64
		formatString: 0
		lineageTag: b176df3e-f030-4fc3-a8c2-36ac11e434ad
		summarizeBy: count
		sourceColumn: Transaction ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 39ae7dae-a281-450b-adc2-c703cf0ad840
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: c1db791f-e56c-472f-bd2d-37a7021cd85f
			defaultHierarchy: LocalDateTable_3656709a-8f99-4c45-ae5a-9c234ecb1d6c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer ID'
		dataType: string
		lineageTag: ba454796-06f2-44ea-896b-0f1069c4b30e
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 748b7d49-01cb-4069-9752-503fe1f7f900
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 6a6e2313-5b96-4545-b775-9bc39af8a699
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: 3b1ba79a-a3d9-4041-96ab-332678558b05
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: a26180c5-c00c-42ff-b776-796a9d520cb6
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Price per Unit'
		dataType: int64
		formatString: 0
		lineageTag: b59810d3-75ff-4679-83ff-485421dece67
		summarizeBy: sum
		sourceColumn: Price per Unit

		annotation SummarizationSetBy = Automatic

	column 'Total Amount'
		dataType: int64
		formatString: 0
		lineageTag: 1d8aadee-6f12-493a-b44e-edcda9188951
		summarizeBy: sum
		sourceColumn: Total Amount

		annotation SummarizationSetBy = Automatic

	partition retail_sales_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\LENOVO\Downloads\retail_sales_dataset.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Transaction ID", Int64.Type}, {"Date", type date}, {"Customer ID", type text}, {"Gender", type text}, {"Age", Int64.Type}, {"Product Category", type text}, {"Quantity", Int64.Type}, {"Price per Unit", Int64.Type}, {"Total Amount", Int64.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Date", Order.Ascending}, {"Transaction ID", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

